# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Telstra Assingment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.0.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'NVActivityIndicatorView'
  # Pods for Telstra Assingment

  target 'Telstra AssingmentTests' do
    inherit! :search_paths
	
    # Pods for testing
  end

  target 'Telstra AssingmentUITests' do
    # Pods for testing
  end

end
