# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Telstra Assingment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.0.1'
  pod 'SDWebImage', '~> 5.0'
  pod 'NVActivityIndicatorView'
  pod 'SwiftLint', '~> 0.32.0'
  # Pods for Telstra Assingment

  target 'Telstra AssingmentTests' do
    inherit! :search_paths
	
    # Pods for testing
  end

end
